// Generated by Kukicha v1.0.0 (requires Go 1.25+)
//
// Performance options:
//   GOEXPERIMENT=greenteagc  - Green Tea GC (10-40% faster, default in Go 1.26)
//   GOEXPERIMENT=jsonv2      - Faster JSON parsing (2-10x improvement)

package string

import "strings"

func ToUpper(s string) string {
	return strings.ToUpper(s)
}

func ToLower(s string) string {
	return strings.ToLower(s)
}

func Title(s string) string {
	return strings.Title(s)
}

func Trim(s string, cutset string) string {
	return strings.Trim(s, cutset)
}

func TrimSpace(s string) string {
	return strings.TrimSpace(s)
}

func TrimPrefix(s string, prefix string) string {
	return strings.TrimPrefix(s, prefix)
}

func TrimSuffix(s string, suffix string) string {
	return strings.TrimSuffix(s, suffix)
}

func TrimLeft(s string, cutset string) string {
	return strings.TrimLeft(s, cutset)
}

func TrimRight(s string, cutset string) string {
	return strings.TrimRight(s, cutset)
}

func Split(s string, sep string) []string {
	return strings.Split(s, sep)
}

func SplitN(s string, sep string, n int) []string {
	return strings.SplitN(s, sep, n)
}

func Join(parts []string, sep string) string {
	return strings.Join(parts, sep)
}

func Fields(s string) []string {
	return strings.Fields(s)
}

func Contains(s string, substr string) bool {
	return strings.Contains(s, substr)
}

func HasPrefix(s string, prefix string) bool {
	return strings.HasPrefix(s, prefix)
}

func HasSuffix(s string, suffix string) bool {
	return strings.HasSuffix(s, suffix)
}

func Index(s string, substr string) int {
	return strings.Index(s, substr)
}

func LastIndex(s string, substr string) int {
	return strings.LastIndex(s, substr)
}

func Count(s string, substr string) int {
	return strings.Count(s, substr)
}

func Replace(s string, old string, new string, n int) string {
	return strings.Replace(s, old, new, n)
}

func ReplaceAll(s string, old string, new string) string {
	return strings.ReplaceAll(s, old, new)
}

func Repeat(s string, count int) string {
	return strings.Repeat(s, count)
}

func EqualFold(s string, t string) bool {
	return strings.EqualFold(s, t)
}

func Len(s string) int {
	return len(s)
}

func IsEmpty(s string) bool {
	return (len(s) == 0)
}

func IsBlank(s string) bool {
	return (len(strings.TrimSpace(s)) == 0)
}

func Lines(s string) []string {
	lines := strings.Split(s, "\n")
	result := make([]string, 0)
	for _, line := range lines {
		result = append(result, line)
	}
	return result
}

func Concat(parts []string) string {
	return strings.Join(parts, "")
}
