// Generated by Kukicha v0.0.5 (requires Go 1.26+)
//
// Performance: GOEXPERIMENT=jsonv2 enables faster JSON parsing (2-10x improvement)

package iterator

import "iter"

//line /home/user/kukicha/stdlib/iterator/iterator.kuki:8
func Filter[T any](seq iter.Seq[T], keep func(T) bool) iter.Seq[T] {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:9
	return func(yield func(T) bool) {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:10
		for item := range seq {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:11
			if keep(item) {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:12
				if !yield(item) {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:13
					return
				}
			}
		}
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:14
		return
	}
}

//line /home/user/kukicha/stdlib/iterator/iterator.kuki:17
func Map[T any, U any](seq iter.Seq[T], transform func(T) U) iter.Seq[U] {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:18
	return func(yield func(U) bool) {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:19
		for item := range seq {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:20
			if !yield(transform(item)) {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:21
				return
			}
		}
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:22
		return
	}
}

//line /home/user/kukicha/stdlib/iterator/iterator.kuki:25
func FlatMap[T any](seq iter.Seq[T], transform func(T) iter.Seq[T]) iter.Seq[T] {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:26
	return func(yield func(T) bool) {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:27
		for item := range seq {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:28
			for subItem := range transform(item) {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:29
				if !yield(subItem) {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:30
					return
				}
			}
		}
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:31
		return
	}
}

//line /home/user/kukicha/stdlib/iterator/iterator.kuki:34
func Take[T any](seq iter.Seq[T], n int) iter.Seq[T] {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:35
	return func(yield func(T) bool) {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:36
		count := 0
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:37
		for item := range seq {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:38
			if count >= n {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:39
				return
			}
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:40
			if !yield(item) {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:41
				return
			}
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:42
			count++
		}
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:43
		return
	}
}

//line /home/user/kukicha/stdlib/iterator/iterator.kuki:46
func Skip[T any](seq iter.Seq[T], n int) iter.Seq[T] {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:47
	return func(yield func(T) bool) {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:48
		count := 0
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:49
		for item := range seq {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:50
			if count >= n {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:51
				if !yield(item) {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:52
					return
				}
			}
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:53
			count++
		}
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:54
		return
	}
}

//line /home/user/kukicha/stdlib/iterator/iterator.kuki:57
func Enumerate[T any](seq iter.Seq[T]) iter.Seq2[int, T] {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:58
	return func(yield func(int, T) bool) {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:59
		i := 0
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:60
		for item := range seq {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:61
			if !yield(i, item) {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:62
				return
			}
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:63
			i++
		}
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:64
		return
	}
}

//line /home/user/kukicha/stdlib/iterator/iterator.kuki:67
func Chunk[T any](seq iter.Seq[T], n int) iter.Seq[[]T] {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:68
	return func(yield func([]T) bool) {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:69
		chunk := make([]T, 0)
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:70
		for item := range seq {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:71
			chunk = append(chunk, item)
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:72
			if len(chunk) == n {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:73
				if !yield(chunk) {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:74
					return
				}
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:75
				chunk = make([]T, 0)
			}
		}
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:77
		if len(chunk) > 0 {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:78
			yield(chunk)
		}
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:79
		return
	}
}

//line /home/user/kukicha/stdlib/iterator/iterator.kuki:83
func Zip[T any](seq1 iter.Seq[T], seq2 iter.Seq[T]) iter.Seq2[T, T] {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:84
	return func(yield func(T, T) bool) {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:85
		done := false
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:86
		for v1 := range seq1 {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:87
			if done {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:88
				return
			}
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:89
			v2Exists := false
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:90
			v2 := *new(T)
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:91
			for v2Candidate := range seq2 {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:92
				v2 = v2Candidate
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:93
				v2Exists = true
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:94
				break
			}
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:95
			if !v2Exists {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:96
				done = true
			} else if !yield(v1, v2) {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:98
				return
			}
		}
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:99
		return
	}
}

//line /home/user/kukicha/stdlib/iterator/iterator.kuki:103
func Reduce[T any](seq iter.Seq[T], initial T, reducer func(T, T) T) T {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:104
	acc := initial
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:105
	for item := range seq {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:106
		acc = reducer(acc, item)
	}
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:107
	return acc
}

//line /home/user/kukicha/stdlib/iterator/iterator.kuki:110
func Collect[T any](seq iter.Seq[T]) []T {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:111
	result := make([]T, 0)
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:112
	for item := range seq {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:113
		result = append(result, item)
	}
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:114
	return result
}

//line /home/user/kukicha/stdlib/iterator/iterator.kuki:117
func Any[T any](seq iter.Seq[T], predicate func(T) bool) bool {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:118
	for item := range seq {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:119
		if predicate(item) {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:120
			return true
		}
	}
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:121
	return false
}

//line /home/user/kukicha/stdlib/iterator/iterator.kuki:124
func All[T any](seq iter.Seq[T], predicate func(T) bool) bool {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:125
	for item := range seq {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:126
		if !predicate(item) {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:127
			return false
		}
	}
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:128
	return true
}

//line /home/user/kukicha/stdlib/iterator/iterator.kuki:132
func Find[T any](seq iter.Seq[T], predicate func(T) bool) (T, bool) {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:133
	for item := range seq {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:134
		if predicate(item) {
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:135
			return item, true
		}
	}
//line /home/user/kukicha/stdlib/iterator/iterator.kuki:136
	return *new(T), false
}
