// Generated by Kukicha v0.0.9 (requires Go 1.26+)

package iterator_test

import (
	"github.com/duber000/kukicha/stdlib/iterator"
	kukistring "github.com/duber000/kukicha/stdlib/string"
	"iter"
	"testing"
)

//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:10
func seqFromStrings[T any](items []string) iter.Seq[T] {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:11
	return func(yield func(T) bool) {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:12
		for _, item := range items {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:13
			if !yield(item) {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:14
				return
			}
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:15
		return
	}
}

//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:17
func collect[T any](seq iter.Seq[T]) []T {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:18
	result := make([]T, 0)
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:19
	for val := range seq {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:20
		result = append(result, val)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:21
	return result
}

//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:24
func TestFilterMapFlatMap(t *testing.T) {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:25
	base := seqFromStrings([]string{"apple", "banana", "cherry"})
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:28
	filtered := iterator.Filter(base, func(item any) bool {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:27
		return (item != "banana")
	})
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:31
	mapped := iterator.Map(filtered, func(item any) any {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:30
		return string.ToUpper(string(item))
	})
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:34
	flat := iterator.FlatMap(mapped, func[T any](item T) iter.Seq[T] {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:33
		return seqFromStrings([]string{string(item), "x"})
	})
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:36
	values := collect(flat)
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:37
	if (len(values) != 4) {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:38
		t.Fatalf("Expected 4 values, got %v", len(values))
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:39
	if (values[0] != "APPLE") {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:40
		t.Errorf("Expected first mapped value to be APPLE")
	}
}

//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:43
func TestTakeSkipEnumerate(t *testing.T) {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:44
	base := seqFromStrings([]string{"a", "b", "c", "d"})
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:45
	taken := iterator.Take(base, 2)
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:46
	takenVals := collect(taken)
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:47
	if (len(takenVals) != 2) {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:48
		t.Errorf("Take returned wrong count")
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:50
	base2 := seqFromStrings([]string{"a", "b", "c"})
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:51
	skipped := iterator.Skip(base2, 1)
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:52
	skippedVals := collect(skipped)
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:53
	if (len(skippedVals) != 2) {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:54
		t.Errorf("Skip returned wrong count")
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:56
	enumerated := iterator.Enumerate(seqFromStrings([]string{"x", "y"}))
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:57
	results := make([]string, 0)
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:58
	for index, item := range enumerated {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:59
		if ((index != 0) && (index != 1)) {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:60
			t.Errorf("Enumerate produced invalid index %v", index)
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:61
		results = append(results, string(item))
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:62
	if (len(results) != 2) {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:63
		t.Errorf("Enumerate returned wrong count")
	}
}

//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:66
func TestChunkZipCollectAnyAllFind(t *testing.T) {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:67
	base := seqFromStrings([]string{"a", "b", "c", "d"})
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:68
	chunks := iterator.Chunk(base, 2)
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:69
	chunked := make([]any, 0)
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:70
	for chunk := range chunks {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:71
		chunked = append(chunked, chunk)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:72
	if (len(chunked) != 2) {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:73
		t.Errorf("Chunk should produce two chunks")
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:75
	seq1 := seqFromStrings([]string{"a", "b"})
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:76
	seq2 := seqFromStrings([]string{"1", "2"})
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:77
	zipped := iterator.Zip(seq1, seq2)
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:78
	pairs := make([]string, 0)
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:79
	for first, second := range zipped {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:80
		pairs = append(pairs, kukistring.Join([]string{string(first), string(second)}, "-"))
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:81
	if (pairs[0] != "a-1") {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:82
		t.Errorf("Zip produced wrong first pair")
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:84
	base2 := seqFromStrings([]string{"ok", "fine"})
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:85
	collected := iterator.Collect(base2)
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:86
	if (len(collected) != 2) {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:87
		t.Errorf("Collect returned wrong count")
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:89
	base3 := seqFromStrings([]string{"one", "two"})
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:90
	if !iterator.Any(base3, func(value any) bool {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:91
		return (string(value) == "two")
	}) {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:93
		t.Errorf("Any should detect existing value")
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:95
	base4 := seqFromStrings([]string{"a", "b"})
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:96
	if !iterator.All(base4, func(value any) bool {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:97
		return (len(string(value)) > 0)
	}) {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:99
		t.Errorf("All should return true when predicate holds")
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:103
	found, ok := iterator.Find(seqFromStrings([]string{"alpha", "beta"}), func(value any) bool {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:102
		return string.HasPrefix(string(value), "b")
	})
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:104
	if (!ok || (found != "beta")) {
//line /var/home/tluker/repos/go/kukicha/stdlib/iterator/iterator_test.kuki:105
		t.Errorf("Find should locate items meeting predicate")
	}
}
