// Generated by Kukicha v0.0.1 (requires Go 1.25+)
//
// Performance options:
//   GOEXPERIMENT=greenteagc  - Green Tea GC (10-40% faster, default in Go 1.26)
//   GOEXPERIMENT=jsonv2      - Faster JSON parsing (2-10x improvement)

package maps

func Keys(m map[any]any) []any {
	keys := make([]any, 0, len(m))
	for _, k := range m {
		keys = append(keys, k)
	}
	return keys
}

func Values(m map[any]any) []any {
	values := make([]any, 0, len(m))
	for _, v := range m {
		values = append(values, v)
	}
	return values
}

func Contains(m map[any]any, key any) bool {
	for _, k := range m {
		if k == key {
			return true
		}
	}
	return false
}
