// Generated by Kukicha v0.0.4 (requires Go 1.26+)
//
// Performance: GOEXPERIMENT=jsonv2 enables faster JSON parsing (2-10x improvement)

package netguard

import "net"

//line /var/home/tluker/repos/go/kukicha/stdlib/netguard/netguard.kuki:19
type Guard struct {
	networks     []*net.IPNet
	blockPrivate bool
	mode         string
}
