// Generated by Kukicha v0.0.1 (requires Go 1.25+)
//
// Performance options:
//   GOEXPERIMENT=greenteagc  - Green Tea GC (10-40% faster, default in Go 1.26)
//   GOEXPERIMENT=jsonv2      - Faster JSON parsing (2-10x improvement)

package must

import (
	"fmt"
	"strconv"

	kukienv "github.com/duber000/kukicha/stdlib/env"
	kukistring "github.com/duber000/kukicha/stdlib/string"
)

func Do(value any, err error) any {
	if err != nil {
		panic(fmt.Sprintf("must: %v", err))
	}
	return value
}

func DoMsg(value any, err error, message string) any {
	if err != nil {
		panic(fmt.Sprintf("%v: %v", message, err))
	}
	return value
}

func Ok(err error) {
	if err != nil {
		panic(fmt.Sprintf("must: %v", err))
	}
}

func OkMsg(err error, message string) {
	if err != nil {
		panic(fmt.Sprintf("%v: %v", message, err))
	}
}

func Env(key string) string {
	value := kukienv.GetOr(key, "")
	if value == "" {
		panic(fmt.Sprintf("must: environment variable %v is required but not set", key))
	}
	return value
}

func EnvOr(key string, defaultValue string) string {
	value := kukienv.GetOr(key, "")
	if value == "" {
		return defaultValue
	}
	return value
}

func EnvInt(key string) int {
	value := kukienv.GetOr(key, "")
	if value == "" {
		panic(fmt.Sprintf("must: environment variable %v is required but not set", key))
	}
	n, err := strconv.Atoi(value)
	if err != nil {
		panic(fmt.Sprintf("must: environment variable %v must be a valid integer, got '%v'", key, value))
	}
	return n
}

func EnvIntOr(key string, defaultValue int) int {
	value := kukienv.GetOr(key, "")
	if value == "" {
		return defaultValue
	}
	n, err := strconv.Atoi(value)
	if err != nil {
		panic(fmt.Sprintf("must: environment variable %v must be a valid integer, got '%v'", key, value))
	}
	return n
}

func EnvBool(key string) bool {
	value := kukienv.GetOr(key, "")
	if value == "" {
		panic(fmt.Sprintf("must: environment variable %v is required but not set", key))
	}
	return parseBool(key, value)
}

func EnvBoolOr(key string, defaultValue bool) bool {
	value := kukienv.GetOr(key, "")
	if value == "" {
		return defaultValue
	}
	return parseBool(key, value)
}

func EnvList(key string, separator string) []string {
	value := kukienv.GetOr(key, "")
	if value == "" {
		panic(fmt.Sprintf("must: environment variable %v is required but not set", key))
	}
	parts := kukistring.Split(value, separator)
	result := make([]string, 0, len(parts))
	for _, part := range parts {
		trimmed := kukistring.TrimSpace(part)
		if trimmed != "" {
			result = append(result, trimmed)
		}
	}
	return result
}

func EnvListOr(key string, separator string, defaultValue []string) []string {
	value := kukienv.GetOr(key, "")
	if value == "" {
		return defaultValue
	}
	parts := kukistring.Split(value, separator)
	result := make([]string, 0, len(parts))
	for _, part := range parts {
		trimmed := kukistring.TrimSpace(part)
		if trimmed != "" {
			result = append(result, trimmed)
		}
	}
	return result
}

func True(condition bool, message string) {
	if !condition {
		panic(fmt.Sprintf("assertion failed: %v", message))
	}
}

func False(condition bool, message string) {
	if condition {
		panic(fmt.Sprintf("assertion failed: %v", message))
	}
}

func NotEmpty(s string, name string) {
	if s == "" {
		panic(fmt.Sprintf("%v cannot be empty", name))
	}
}

func NotNil(value any, name string) {
	if value == nil {
		panic(fmt.Sprintf("%v cannot be nil", name))
	}
}

func parseBool(key string, value string) bool {
	lower := kukistring.ToLower(kukistring.TrimSpace(value))
	if ((lower == "true") || (lower == "1")) || (lower == "yes") {
		return true
	}
	if ((lower == "false") || (lower == "0")) || (lower == "no") {
		return false
	}
	panic(fmt.Sprintf("must: environment variable %v must be a valid boolean, got '%v'", key, value))
}
