// Generated by Kukicha v0.0.1 (requires Go 1.25+)
//
// Performance options:
//   GOEXPERIMENT=greenteagc  - Green Tea GC (10-40% faster, default in Go 1.26)
//   GOEXPERIMENT=jsonv2      - Faster JSON parsing (2-10x improvement)

package main

import "fmt"

func Greet(name string) string {
	return fmt.Sprintf("Hello %v", name)
}

func main() {
	fmt.Println(Greet("World"))
}
