// Generated by Kukicha v1.0.0 (requires Go 1.25+)
//
// Performance options:
//   GOEXPERIMENT=greenteagc  - Green Tea GC (10-40% faster, default in Go 1.26)
//   GOEXPERIMENT=jsonv2      - Faster JSON parsing (2-10x improvement)

package retry

import "time"

type Config struct {
	MaxAttempts  int
	InitialDelay int
	Strategy     int
}

func New() Config {
	return Config{MaxAttempts: 3, InitialDelay: 1000, Strategy: 1}
}

func Attempts(cfg Config, maxAttempts int) Config {
	cfg.MaxAttempts = maxAttempts
	return cfg
}

func Delay(cfg Config, delayMs int) Config {
	cfg.InitialDelay = delayMs
	return cfg
}

func Backoff(cfg Config, strategy int) Config {
	cfg.Strategy = strategy
	return cfg
}

func Sleep(cfg Config, attempt int) {
	delay := calculateDelay(cfg, attempt)
	time.Sleep((time.Duration(delay) * time.Millisecond))
}

func calculateDelay(cfg Config, attempt int) int {
	if cfg.Strategy == 0 {
		return cfg.InitialDelay
	}
	multiplier := 1
	i := 0
	for i < attempt {
		multiplier = (multiplier * 2)
		i = (i + 1)
	}
	return (cfg.InitialDelay * multiplier)
}
