// Generated by Kukicha v0.0.4 (requires Go 1.26+)
//
// Performance: GOEXPERIMENT=jsonv2 enables faster JSON parsing (2-10x improvement)

package obs

import (
	"encoding/json"
	"fmt"
	"github.com/duber000/kukicha/stdlib/random"
	"time"
)

//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:12
type Logger struct {
	service       string
	environment   string
	component     string
	correlationID string
}

//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:19
type Timer struct {
	logger    Logger
	operation string
	startedAt time.Time
}

//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:25
func New(service string, environment string) Logger {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:26
	return Logger{service: service, environment: environment, component: "", correlationID: ""}
}

//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:34
func Component(logger Logger, component string) Logger {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:35
	logger.component = component
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:36
	return logger
}

//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:39
func WithCorrelation(logger Logger, correlationID string) Logger {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:40
	logger.correlationID = correlationID
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:41
	return logger
}

//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:44
func NewCorrelationID() string {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:45
	return random.String(16)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:48
func Debug(logger Logger, message string, fields map[string]any) {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:49
	Log(logger, "debug", message, fields)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:52
func Info(logger Logger, message string, fields map[string]any) {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:53
	Log(logger, "info", message, fields)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:56
func Warn(logger Logger, message string, fields map[string]any) {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:57
	Log(logger, "warn", message, fields)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:60
func Error(logger Logger, message string, fields map[string]any) {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:61
	Log(logger, "error", message, fields)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:64
func Log(logger Logger, level string, message string, fields map[string]any) {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:69
	payload := map[string]any{"ts": time.Now().Format(time.RFC3339Nano), "level": level, "message": message}
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:70
	if logger.service != "" {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:71
		payload["service"] = logger.service
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:72
	if logger.environment != "" {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:73
		payload["environment"] = logger.environment
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:74
	if logger.component != "" {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:75
		payload["component"] = logger.component
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:76
	if logger.correlationID != "" {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:77
		payload["correlation_id"] = logger.correlationID
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:78
	if fields != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:79
		for key, value := range fields {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:80
			payload[key] = value
		}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:82
	line, err := json.Marshal(payload)
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:83
	if err != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:84
		fmt.Println(fmt.Sprintf("[obs:%v] %v", level, message))
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:85
		return
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:86
	fmt.Printf("%s\n", line)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:89
func Start(logger Logger, operation string) Timer {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:90
	return Timer{logger: logger, operation: operation, startedAt: time.Now()}
}

//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:97
func Stop(timer Timer, fields map[string]any) {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:98
	elapsedMs := time.Since(timer.startedAt).Milliseconds()
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:99
	if fields == nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:100
		fields = map[string]any{}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:101
	fields["operation"] = timer.operation
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:102
	fields["duration_ms"] = elapsedMs
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:103
	Info(timer.logger, "operation complete", fields)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:106
func Fail(timer Timer, reason string, fields map[string]any) {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:107
	elapsedMs := time.Since(timer.startedAt).Milliseconds()
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:108
	if fields == nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:109
		fields = map[string]any{}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:110
	fields["operation"] = timer.operation
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:111
	fields["duration_ms"] = elapsedMs
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:112
	fields["reason"] = reason
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs.kuki:113
	Error(timer.logger, "operation failed", fields)
}
