// Generated by Kukicha v0.0.9 (requires Go 1.26+)

package obs_test

import (
	"github.com/duber000/kukicha/stdlib/obs"
	"testing"
)

//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs_test.kuki:9
func TestLoggerFields(t *testing.T) {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs_test.kuki:10
	logger := obs.New("svc", "env")
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs_test.kuki:11
	logger = obs.Component(logger, "api")
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs_test.kuki:12
	logger = obs.WithCorrelation(logger, "cid")
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs_test.kuki:14
	if logger.service != "svc" {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs_test.kuki:15
		t.Errorf("Service should remain set")
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs_test.kuki:16
	if logger.environment != "env" {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs_test.kuki:17
		t.Errorf("Environment should remain set")
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs_test.kuki:18
	if logger.correlationID != "cid" {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs_test.kuki:19
		t.Errorf("Correlation ID should be applied")
	}
}

//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs_test.kuki:22
func TestCorrelationID(t *testing.T) {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs_test.kuki:23
	id := obs.NewCorrelationID()
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs_test.kuki:24
	if len(id) != 16 {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs_test.kuki:25
		t.Errorf("Correlation IDs should be 16 chars long")
	}
}

//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs_test.kuki:28
func TestTimerStopFail(t *testing.T) {
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs_test.kuki:29
	logger := obs.New("svc", "env")
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs_test.kuki:30
	timer := obs.Start(logger, "op")
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs_test.kuki:31
	obs.Stop(timer, map[string]any{})
//line /var/home/tluker/repos/go/kukicha/stdlib/obs/obs_test.kuki:32
	obs.Fail(timer, "error", map[string]any{})
}
