// Generated by Kukicha v0.0.5 (requires Go 1.26+)

package json

import (
	"encoding/json"
	"fmt"
	"io"
)

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:10
type Encoder struct {
	writer        io.Writer
	deterministic bool
	indent        string
	prefix        string
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:17
type Decoder struct {
	reader io.Reader
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:23
func NewEncoder(writer io.Writer) Encoder {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:24
	enc := Encoder{}
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:25
	enc.writer = writer
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:26
	enc.deterministic = false
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:27
	enc.indent = ""
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:28
	enc.prefix = ""
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:29
	return enc
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:34
func WithDeterministic(enc Encoder) Encoder {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:35
	enc.deterministic = true
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:36
	return enc
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:41
func WithIndent(enc Encoder, indent string) Encoder {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:42
	enc.indent = indent
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:43
	return enc
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:47
func WithPrefix(enc Encoder, prefix string) Encoder {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:48
	enc.prefix = prefix
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:49
	return enc
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:57
func Encode(enc Encoder, value any) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:59
	encoder := json.NewEncoder(enc.writer)
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:60
	return encoder.Encode(value)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:65
func NewDecoder(reader io.Reader) Decoder {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:66
	dec := Decoder{}
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:67
	dec.reader = reader
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:68
	return dec
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:74
func Decode(dec Decoder, target any) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:75
	decoder := json.NewDecoder(dec.reader)
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:76
	return decoder.Decode(target)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:82
func Marshal(value any) ([]byte, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:83
	bytes, err := json.Marshal(value)
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:84
	return bytes, err
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:89
func MarshalPretty(value any) ([]byte, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:90
	bytes, err := json.MarshalIndent(value, "", "  ")
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:91
	return bytes, err
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:97
func Unmarshal(data []byte, target any) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:98
	return json.Unmarshal(data, target)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:104
func MarshalWrite(writer io.Writer, value any) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:105
	encoder := json.NewEncoder(writer)
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:106
	return encoder.Encode(value)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:112
func UnmarshalRead(reader io.Reader, target any) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:113
	decoder := json.NewDecoder(reader)
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:114
	return decoder.Decode(target)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:119
func DecodeRead[T any](reader io.Reader, sample T) (T, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:120
	data := sample
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:121
	decoder := json.NewDecoder(reader)
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:122
	if err_1 := decoder.Decode(&data); err_1 != nil {
		err_1 = fmt.Errorf("failed to decode json: %w", err_1)
		return *new(T), err_1
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:123
	return data, nil
}
