// Generated by Kukicha v0.0.4 (requires Go 1.26+)
//
// Performance: GOEXPERIMENT=jsonv2 enables faster JSON parsing (2-10x improvement)

package json

import (
	jsonv1 "encoding/json"
	json "encoding/json/v2"
	"fmt"
	"io"
)

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:12
type Encoder struct {
	writer        io.Writer
	deterministic bool
	indent        string
	prefix        string
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:19
type Decoder struct {
	reader io.Reader
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:25
func NewEncoder(writer io.Writer) Encoder {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:26
	enc := Encoder{}
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:27
	enc.writer = writer
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:28
	enc.deterministic = false
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:29
	enc.indent = ""
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:30
	enc.prefix = ""
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:31
	return enc
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:36
func WithDeterministic(enc Encoder) Encoder {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:37
	enc.deterministic = true
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:38
	return enc
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:43
func WithIndent(enc Encoder, indent string) Encoder {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:44
	enc.indent = indent
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:45
	return enc
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:49
func WithPrefix(enc Encoder, prefix string) Encoder {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:50
	enc.prefix = prefix
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:51
	return enc
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:59
func Encode(enc Encoder, value any) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:61
	if enc.deterministic {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:62
		return json.MarshalWrite(enc.writer, value, json.Deterministic(true))
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:65
	return json.MarshalWrite(enc.writer, value)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:70
func NewDecoder(reader io.Reader) Decoder {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:71
	dec := Decoder{}
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:72
	dec.reader = reader
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:73
	return dec
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:80
func Decode(dec Decoder, target any) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:81
	return json.UnmarshalRead(dec.reader, target)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:88
func Marshal(value any) ([]byte, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:89
	bytes, err := json.Marshal(value)
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:90
	return bytes, err
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:97
func MarshalPretty(value any) ([]byte, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:100
	bytes, err := jsonv1.MarshalIndent(value, "", "  ")
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:101
	return bytes, err
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:108
func Unmarshal(data []byte, target any) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:109
	return json.Unmarshal(data, target)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:115
func MarshalWrite(writer io.Writer, value any) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:116
	return json.MarshalWrite(writer, value)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:123
func UnmarshalRead(reader io.Reader, target any) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:124
	return json.UnmarshalRead(reader, target)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:129
func DecodeRead(reader io.Reader, sample any) (any, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:130
	data := sample
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:131
	if err_1 := json.UnmarshalRead(reader, &data); err_1 != nil {
		err_1 = fmt.Errorf("failed to decode json: %w", err_1)
		return *new(any), err_1
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/json/json.kuki:132
	return data, nil
}
