// Generated by Kukicha v0.0.9 (requires Go 1.26+)

package random_test

import (
	"github.com/duber000/kukicha/stdlib/random"
	"testing"
)

//line /var/home/tluker/repos/go/kukicha/stdlib/random/random_test.kuki:9
func TestRandomStringLength(t *testing.T) {
//line /var/home/tluker/repos/go/kukicha/stdlib/random/random_test.kuki:10
	s := random.String(10)
//line /var/home/tluker/repos/go/kukicha/stdlib/random/random_test.kuki:11
	if len(s) != 10 {
//line /var/home/tluker/repos/go/kukicha/stdlib/random/random_test.kuki:12
		t.Errorf("Expected random string length 10, got %v", len(s))
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/random/random_test.kuki:14
	zero := random.String(0)
//line /var/home/tluker/repos/go/kukicha/stdlib/random/random_test.kuki:15
	if zero != "" {
//line /var/home/tluker/repos/go/kukicha/stdlib/random/random_test.kuki:16
		t.Errorf("Expected empty string when length 0, got '%v'", zero)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/random/random_test.kuki:18
	alpha := random.Alphanumeric(5)
//line /var/home/tluker/repos/go/kukicha/stdlib/random/random_test.kuki:19
	if len(alpha) != 5 {
//line /var/home/tluker/repos/go/kukicha/stdlib/random/random_test.kuki:20
		t.Errorf("Expected alphanumeric length 5, got %v", len(alpha))
	}
}
