// Generated by Kukicha v0.0.9 (requires Go 1.26+)

package concurrent_test

import (
	"github.com/duber000/kukicha/stdlib/concurrent"
	"testing"
)

//line /var/home/tluker/repos/go/kukicha/stdlib/concurrent/concurrent_test.kuki:9
func TestFunctionsExist(t *testing.T) {
//line /var/home/tluker/repos/go/kukicha/stdlib/concurrent/concurrent_test.kuki:11
	if concurrent.Parallel == nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/concurrent/concurrent_test.kuki:12
		t.Error("Expected Parallel function to exist")
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/concurrent/concurrent_test.kuki:15
	if concurrent.ParallelWithLimit == nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/concurrent/concurrent_test.kuki:16
		t.Error("Expected ParallelWithLimit function to exist")
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/concurrent/concurrent_test.kuki:19
	if concurrent.Go == nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/concurrent/concurrent_test.kuki:20
		t.Error("Expected Go function to exist")
	}
}

//line /var/home/tluker/repos/go/kukicha/stdlib/concurrent/concurrent_test.kuki:23
func TestParallelEmpty(t *testing.T) {
//line /var/home/tluker/repos/go/kukicha/stdlib/concurrent/concurrent_test.kuki:24
	emptyTasks := []func(){}
//line /var/home/tluker/repos/go/kukicha/stdlib/concurrent/concurrent_test.kuki:25
	concurrent.Parallel(emptyTasks...)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/concurrent/concurrent_test.kuki:29
func TestParallelWithLimitEmpty(t *testing.T) {
//line /var/home/tluker/repos/go/kukicha/stdlib/concurrent/concurrent_test.kuki:30
	emptyTasks := []func(){}
//line /var/home/tluker/repos/go/kukicha/stdlib/concurrent/concurrent_test.kuki:31
	concurrent.ParallelWithLimit(5, emptyTasks...)
}
