// Generated by Kukicha v1.0.0 (requires Go 1.25+)
//
// Performance options:
//   GOEXPERIMENT=greenteagc  - Green Tea GC (10-40% faster, default in Go 1.26)
//   GOEXPERIMENT=jsonv2      - Faster JSON parsing (2-10x improvement)

package concurrent

import "sync"

func Parallel(tasks ...func()) {
	wg := sync.WaitGroup{}
	wg.Add(len(tasks))
	for _, task := range tasks {
		t := task
		go func() {
			t()
			wg.Done()
		}()
	}
	wg.Wait()
}

func ParallelWithLimit(limit int, tasks ...func()) {
	wg := sync.WaitGroup{}
	semaphore := make(chan int, limit)
	wg.Add(len(tasks))
	for _, task := range tasks {
		semaphore <- 1
		t := task
		go func() {
			t()
			<-semaphore
			wg.Done()
		}()
	}
	wg.Wait()
}

func Go(fn func()) {
	go fn()
}
