// Generated by Kukicha v0.0.8 (requires Go 1.26+)

package errors

import (
	goerrors "errors"
	"fmt"
)

//line /Users/tluker/repos/go/kukicha/stdlib/errors/errors.kuki:22
func Wrap(err error, msg string) error {
//line /Users/tluker/repos/go/kukicha/stdlib/errors/errors.kuki:23
	return fmt.Errorf("%s: %w", msg, err)
}

//line /Users/tluker/repos/go/kukicha/stdlib/errors/errors.kuki:27
func Is(err error, target error) bool {
//line /Users/tluker/repos/go/kukicha/stdlib/errors/errors.kuki:28
	return goerrors.Is(err, target)
}

//line /Users/tluker/repos/go/kukicha/stdlib/errors/errors.kuki:33
func Unwrap(err error) error {
//line /Users/tluker/repos/go/kukicha/stdlib/errors/errors.kuki:34
	return goerrors.Unwrap(err)
}

//line /Users/tluker/repos/go/kukicha/stdlib/errors/errors.kuki:38
func New(msg string) error {
//line /Users/tluker/repos/go/kukicha/stdlib/errors/errors.kuki:39
	return goerrors.New(msg)
}

//line /Users/tluker/repos/go/kukicha/stdlib/errors/errors.kuki:43
func Join(items ...error) error {
//line /Users/tluker/repos/go/kukicha/stdlib/errors/errors.kuki:44
	return goerrors.Join(items...)
}
