// Generated by Kukicha v0.0.9 (requires Go 1.26+)

package errors_test

import (
	goerrors "errors"
	"github.com/duber000/kukicha/stdlib/errors"
	"testing"
)

//line /var/home/tluker/repos/go/kukicha/stdlib/errors/errors_test.kuki:10
func TestWrapAndIs(t *testing.T) {
//line /var/home/tluker/repos/go/kukicha/stdlib/errors/errors_test.kuki:11
	base := goerrors.New("base")
//line /var/home/tluker/repos/go/kukicha/stdlib/errors/errors_test.kuki:12
	wrapped := errors.Wrap(base, "context")
//line /var/home/tluker/repos/go/kukicha/stdlib/errors/errors_test.kuki:13
	if !errors.Is(wrapped, base) {
//line /var/home/tluker/repos/go/kukicha/stdlib/errors/errors_test.kuki:14
		t.Errorf("Wrap/Is failed to identify base error")
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/errors/errors_test.kuki:16
	unwrapped := errors.Unwrap(wrapped)
//line /var/home/tluker/repos/go/kukicha/stdlib/errors/errors_test.kuki:17
	if unwrapped != base {
//line /var/home/tluker/repos/go/kukicha/stdlib/errors/errors_test.kuki:18
		t.Errorf("Unwrap did not return base error")
	}
}

//line /var/home/tluker/repos/go/kukicha/stdlib/errors/errors_test.kuki:21
func TestJoin(t *testing.T) {
//line /var/home/tluker/repos/go/kukicha/stdlib/errors/errors_test.kuki:22
	aErr := goerrors.New("a")
//line /var/home/tluker/repos/go/kukicha/stdlib/errors/errors_test.kuki:23
	bErr := goerrors.New("b")
//line /var/home/tluker/repos/go/kukicha/stdlib/errors/errors_test.kuki:24
	e := errors.Join(aErr, bErr)
//line /var/home/tluker/repos/go/kukicha/stdlib/errors/errors_test.kuki:25
	if e == nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/errors/errors_test.kuki:26
		t.Fatalf("Join should return aggregated error")
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/errors/errors_test.kuki:27
	if !errors.Is(e, aErr) {
//line /var/home/tluker/repos/go/kukicha/stdlib/errors/errors_test.kuki:28
		t.Errorf("Join should preserve original errors")
	}
}
