// Generated by Kukicha v0.0.5 (requires Go 1.26+)
//
// Performance: GOEXPERIMENT=jsonv2 enables faster JSON parsing (2-10x improvement)

package main

import (
	"fmt"
	"github.com/duber000/kukicha/stdlib/cast"
	"github.com/duber000/kukicha/stdlib/cli"
	"github.com/duber000/kukicha/stdlib/json"
	"github.com/duber000/kukicha/stdlib/kube"
	kukistring "github.com/duber000/kukicha/stdlib/string"
)

//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:12
func main() {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:13
	app := cli.New("ku-k8s")
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:15
	app = cli.Arg(app, "command", "Subcommand: get-unready-logs, analyze-crash")
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:16
	app = cli.Arg(app, "deployment", "Name of the deployment")
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:17
	app = cli.AddFlag(app, "namespace", "Kubernetes namespace", "default")
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:18
	app = cli.AddFlag(app, "tail", "Number of log lines to tail per pod", "50")
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:20
	app = cli.Action(app, runAppAction)
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:22
	err := cli.RunApp(app)
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:23
	if err != nil {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:24
		fmt.Println(fmt.Sprintf("{{\"error\": \"CLI Run failed: %v\"}}", err))
	}
}

//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:26
func runAppAction(args cli.Args) {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:27
	command := cli.GetString(args, "command")
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:28
	deployment := cli.GetString(args, "deployment")
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:29
	tailStr := cli.GetString(args, "tail")
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:30
	namespace := cli.GetString(args, "namespace")
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:32
	tailLines, err := cast.SmartInt(tailStr)
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:33
	if err != nil {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:34
		tailLines = 50
	}
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:36
	cluster, connectErr := kube.Connect()
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:37
	if connectErr != nil {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:38
		fmt.Println(fmt.Sprintf("{{\"error\": \"Failed to connect to cluster: %v\"}}", connectErr))
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:39
		return
	}
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:41
	cluster = kube.Namespace(cluster, namespace)
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:43
	if command == "get-unready-logs" {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:44
		handleUnreadyLogs(cluster, deployment, tailLines)
	} else if command == "analyze-crash" {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:46
		handleAnalyze(cluster, deployment)
	} else {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:48
		fmt.Println("{{\"error\": \"Unknown command or missing arguments. Use get-unready-logs or analyze-crash.\"}}")
	}
}

//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:50
func handleUnreadyLogs(cluster kube.Cluster, deployment string, tailLines int) {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:51
	if deployment == "" {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:52
		fmt.Println("{{\"error\": \"Deployment name is required\"}}")
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:53
		return
	}
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:55
	podsList, listErr := kube.ListPods(cluster)
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:56
	if listErr != nil {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:57
		fmt.Println(fmt.Sprintf("{{\"error\": \"Failed to list pods: %v\"}}", listErr))
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:58
		return
	}
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:60
	unreadyPodsData := make([]map[string]string, 0)
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:62
	for _, p := range kube.Pods(podsList) {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:63
		name := kube.PodName(p)
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:64
		if kukistring.HasPrefix(name, (deployment + "-")) {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:65
			if !kube.PodReady(p) {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:66
				logs, logErr := kube.PodLogsTail(cluster, name, int64(tailLines))
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:67
				if logErr != nil {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:68
					logs = fmt.Sprintf("Error fetching logs: %v", logErr)
				}
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:75
				podData := map[string]string{"name": name, "status": kube.PodStatus(p), "restarts": fmt.Sprintf("%d", kube.PodRestarts(p)), "logs": logs}
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:76
				unreadyPodsData = append(unreadyPodsData, podData)
			}
		}
	}
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:84
	result := map[string]any{"status": "success", "action": "get_unready_logs", "deployment": deployment, "unready_pods_count": len(unreadyPodsData), "pods": unreadyPodsData}
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:86
	if len(unreadyPodsData) == 0 {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:87
		result["message"] = fmt.Sprintf("All pods for deployment %v are currently in a Ready state.", deployment)
	} else {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:89
		result["message"] = fmt.Sprintf("Found %v unready pods for deployment %v.", len(unreadyPodsData), deployment)
	}
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:91
	out, jsonErr := json.Marshal(result)
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:92
	if jsonErr != nil {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:93
		fmt.Println("{{\"error\": \"Failed to marshal result\"}}")
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:94
		return
	}
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:96
	s, castErr := cast.SmartString(out)
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:97
	if castErr != nil {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:98
		fmt.Println("{{\"error\": \"Failed to format output\"}}")
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:99
		return
	}
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:101
	fmt.Println(s)
}

//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:103
func handleAnalyze(cluster kube.Cluster, deployment string) {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:104
	if deployment == "" {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:105
		fmt.Println("{{\"error\": \"Deployment name is required\"}}")
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:106
		return
	}
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:108
	podsList, listErr := kube.ListPods(cluster)
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:109
	if listErr != nil {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:110
		fmt.Println(fmt.Sprintf("{{\"error\": \"Failed to list pods: %v\"}}", listErr))
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:111
		return
	}
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:113
	crashingPods := make([]map[string]string, 0)
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:115
	for _, p := range kube.Pods(podsList) {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:116
		name := kube.PodName(p)
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:117
		if kukistring.HasPrefix(name, (deployment + "-")) {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:118
			status := kube.PodStatus(p)
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:119
			if (status != "Running") && (status != "Succeeded") {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:126
				podData := map[string]string{"name": name, "status": status, "restarts": fmt.Sprintf("%d", kube.PodRestarts(p)), "node": kube.PodNode(p), "age": kube.PodAge(p)}
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:127
				crashingPods = append(crashingPods, podData)
			}
		}
	}
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:133
	result := map[string]any{"deployment": deployment, "crashing_pods_count": len(crashingPods), "pods": crashingPods}
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:135
	if len(crashingPods) == 0 {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:136
		result["simulation_note"] = "No crashing pods found with that prefix natively matching 'Running'/'Succeeded' conditions. In a live system, Goose would see OOMKilled pods here."
	}
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:138
	out, jsonErr := json.Marshal(result)
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:139
	if jsonErr != nil {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:140
		fmt.Println("{{\"error\": \"Failed to marshal result\"}}")
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:141
		return
	}
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:143
	s, castErr := cast.SmartString(out)
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:144
	if castErr != nil {
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:145
		fmt.Println("{{\"error\": \"Failed to format output\"}}")
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:146
		return
	}
//line /var/home/tluker/repos/go/kukicha/cmd/ku-k8s/main.kuki:148
	fmt.Println(s)
}
