// Generated by Kukicha v0.0.4 (requires Go 1.26+)
//
// Performance: GOEXPERIMENT=jsonv2 enables faster JSON parsing (2-10x improvement)

package a2a

//line /var/home/tluker/repos/go/kukicha/stdlib/a2a/a2a.kuki:6
type Task struct {
	ID        string
	ContextID string
	State     string
	Text      string
	Artifacts []Artifact
}

//line /var/home/tluker/repos/go/kukicha/stdlib/a2a/a2a.kuki:14
type Artifact struct {
	Name string
	Text string
}

//line /var/home/tluker/repos/go/kukicha/stdlib/a2a/a2a.kuki:19
type StatusUpdate struct {
	TaskID  string
	State   string
	Message string
	Final   bool
}

//line /var/home/tluker/repos/go/kukicha/stdlib/a2a/a2a.kuki:26
type Skill struct {
	Name        string
	Description string
	Examples    []string
}
