// Generated by Kukicha v0.0.4 (requires Go 1.26+)
//
// Performance: GOEXPERIMENT=jsonv2 enables faster JSON parsing (2-10x improvement)

package main

import "fmt"

//line /var/home/tluker/repos/go/kukicha/examples/parse-demo/main.kuki:3
type Config struct {
	Name    string `json:"name"`
	Version string `json:"version"`
	Debug   bool   `json:"debug"`
}

//line /var/home/tluker/repos/go/kukicha/examples/parse-demo/main.kuki:8
func main() {
//line /var/home/tluker/repos/go/kukicha/examples/parse-demo/main.kuki:10
	config := Config{Name: "myapp", Version: "1.0.0", Debug: true}
//line /var/home/tluker/repos/go/kukicha/examples/parse-demo/main.kuki:12
	fmt.Println("Struct with tags created successfully")
//line /var/home/tluker/repos/go/kukicha/examples/parse-demo/main.kuki:13
	fmt.Println(config.Name)
//line /var/home/tluker/repos/go/kukicha/examples/parse-demo/main.kuki:14
	fmt.Println("JSON tags work!")
}
