// Generated by Kukicha v0.0.4 (requires Go 1.26+)
//
// Performance: GOEXPERIMENT=jsonv2 enables faster JSON parsing (2-10x improvement)

package slice

import (
	"errors"
	"fmt"
	"slices"
)

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:10
func First(items []any, n int) []any {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:11
	if n <= 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:12
		return make([]any, 0)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:13
	if n >= len(items) {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:14
		return items
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:15
	return items[:n]
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:19
func Last(items []any, n int) []any {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:20
	length := len(items)
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:21
	if n <= 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:22
		return make([]any, 0)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:23
	if n >= length {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:24
		return items
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:25
	return items[(length - n):]
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:29
func Drop(items []any, n int) []any {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:30
	if n <= 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:31
		return items
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:32
	if n >= len(items) {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:33
		return make([]any, 0)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:34
	return items[n:]
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:38
func DropLast(items []any, n int) []any {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:39
	length := len(items)
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:40
	if n <= 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:41
		return items
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:42
	if n >= length {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:43
		return make([]any, 0)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:44
	return items[:(length - n)]
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:48
func Reverse(items []any) []any {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:49
	result := slices.Clone(items)
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:50
	slices.Reverse(result)
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:51
	return result
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:56
func Unique(items []any) []any {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:57
	if len(items) == 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:58
		return items
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:60
	seen := make(map[any]bool)
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:61
	result := make([]any, 0)
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:63
	for _, item := range items {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:64
		if !seen[item] {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:65
			seen[item] = true
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:66
			result = append(result, item)
		}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:68
	return result
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:72
func Chunk(items []any, size int) [][]any {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:73
	if size <= 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:74
		return make([][]any, 0)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:76
	result := make([][]any, 0)
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:77
	length := len(items)
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:78
	i := 0
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:80
	for i < length {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:81
		end := (i + size)
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:82
		if end > length {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:83
			end = length
		}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:84
		chunk := items[i:end]
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:85
		result = append(result, chunk)
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:86
		i = (i + size)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:88
	return result
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:92
func Contains(items []any, value any) bool {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:93
	return slices.Contains(items, value)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:98
func IndexOf(items []any, value any) int {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:99
	return slices.Index(items, value)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:103
func Concat(slices [][]any) []any {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:104
	totalLength := 0
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:105
	for _, slice := range slices {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:106
		totalLength = (totalLength + len(slice))
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:108
	result := make([]any, 0, totalLength)
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:109
	for _, slice := range slices {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:110
		for _, item := range slice {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:111
			result = append(result, item)
		}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:113
	return result
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:117
func Filter(items []any, predicate func(any) bool) []any {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:118
	result := make([]any, 0)
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:119
	for _, item := range items {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:120
		if predicate(item) {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:121
			result = append(result, item)
		}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:122
	return result
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:126
func Map(items []any, transform func(any) any) []any {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:127
	result := make([]any, len(items))
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:128
	for i, item := range items {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:129
		result[i] = transform(item)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:130
	return result
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:135
func GroupBy[T any, K comparable](items []T, keyFunc func(T) K) map[K][]T {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:136
	result := make(map[K][]T)
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:137
	for _, item := range items {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:138
		key := keyFunc(item)
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:139
		result[key] = append(result[key], item)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:140
	return result
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:148
func Get(items []any, index int) (any, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:149
	length := len(items)
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:150
	if length == 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:151
		return nil, errors.New("slice is empty")
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:154
	actualIndex := index
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:155
	if index < 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:156
		actualIndex = (length + index)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:158
	if (actualIndex < 0) || (actualIndex >= length) {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:159
		return nil, errors.New(fmt.Sprintf("index %v out of bounds for slice of length %v", index, length))
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:161
	return items[actualIndex], nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:167
func GetOr(items []any, index int, defaultValue any) any {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:168
	length := len(items)
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:169
	if length == 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:170
		return defaultValue
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:173
	actualIndex := index
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:174
	if index < 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:175
		actualIndex = (length + index)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:177
	if (actualIndex < 0) || (actualIndex >= length) {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:178
		return defaultValue
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:180
	return items[actualIndex]
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:184
func FirstOne(items []any) (any, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:185
	if len(items) == 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:186
		return nil, errors.New("slice is empty")
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:187
	return items[0], nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:192
func FirstOr(items []any, defaultValue any) any {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:193
	if len(items) == 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:194
		return defaultValue
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:195
	return items[0]
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:199
func LastOne(items []any) (any, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:200
	if len(items) == 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:201
		return nil, errors.New("slice is empty")
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:202
	return items[(len(items) - 1)], nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:207
func LastOr(items []any, defaultValue any) any {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:208
	if len(items) == 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:209
		return defaultValue
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:210
	return items[(len(items) - 1)]
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:214
func Find(items []any, predicate func(any) bool) (any, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:215
	for _, item := range items {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:216
		if predicate(item) {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:217
			return item, nil
		}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:218
	return nil, errors.New("no matching element found")
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:223
func FindOr(items []any, predicate func(any) bool, defaultValue any) any {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:224
	for _, item := range items {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:225
		if predicate(item) {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:226
			return item
		}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:227
	return defaultValue
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:232
func FindIndex(items []any, predicate func(any) bool) int {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:233
	for i, item := range items {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:234
		if predicate(item) {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:235
			return i
		}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:236
	return -1
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:240
func FindLast(items []any, predicate func(any) bool) (any, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:241
	for i := (len(items) - 1); i <= 0; i++ {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:242
		if predicate(items[i]) {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:243
			return items[i], nil
		}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:244
	return nil, errors.New("no matching element found")
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:248
func FindLastOr(items []any, predicate func(any) bool, defaultValue any) any {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:249
	for i := (len(items) - 1); i <= 0; i++ {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:250
		if predicate(items[i]) {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:251
			return items[i]
		}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:252
	return defaultValue
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:256
func IsEmpty(items []any) bool {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:257
	return (len(items) == 0)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:261
func IsNotEmpty(items []any) bool {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:262
	return (len(items) > 0)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:267
func Pop(items []any) (any, []any, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:268
	if len(items) == 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:269
		return nil, items, errors.New("cannot pop from empty slice")
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:270
	return items[(len(items) - 1)], items[:(len(items) - 1)], nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:275
func Shift(items []any) (any, []any, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:276
	if len(items) == 0 {
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:277
		return nil, items, errors.New("cannot shift from empty slice")
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/slice/slice.kuki:278
	return items[0], items[1:], nil
}
