// Generated by Kukicha v0.0.4 (requires Go 1.26+)
//
// Performance: GOEXPERIMENT=jsonv2 enables faster JSON parsing (2-10x improvement)

package mcp

import (
	"context"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

//line /var/home/tluker/repos/go/kukicha/stdlib/mcp/mcp.kuki:9
type SchemaProperty struct {
	Name        string
	Type        string
	Description string
}

//line /var/home/tluker/repos/go/kukicha/stdlib/mcp/mcp.kuki:15
func New(name string, version string) *mcp.Server {
//line /var/home/tluker/repos/go/kukicha/stdlib/mcp/mcp.kuki:16
	return mcp.NewServer(&mcp.Implementation{Name: name, Version: version}, nil)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/mcp/mcp.kuki:22
func Serve(server *mcp.Server) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/mcp/mcp.kuki:23
	return server.Run(context.Background(), &mcp.StdioTransport{})
}

//line /var/home/tluker/repos/go/kukicha/stdlib/mcp/mcp.kuki:26
func Prop(name string, typ string, description string) SchemaProperty {
//line /var/home/tluker/repos/go/kukicha/stdlib/mcp/mcp.kuki:27
	return SchemaProperty{Name: name, Type: typ, Description: description}
}

//line /var/home/tluker/repos/go/kukicha/stdlib/mcp/mcp.kuki:30
func Schema(props []SchemaProperty) map[string]any {
//line /var/home/tluker/repos/go/kukicha/stdlib/mcp/mcp.kuki:31
	properties := make(map[string]any)
//line /var/home/tluker/repos/go/kukicha/stdlib/mcp/mcp.kuki:32
	for _, prop := range props {
//line /var/home/tluker/repos/go/kukicha/stdlib/mcp/mcp.kuki:36
		properties[prop.Name] = map[string]any{"type": prop.Type, "description": prop.Description}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/mcp/mcp.kuki:38
	return map[string]any{"type": "object", "properties": properties}
}

//line /var/home/tluker/repos/go/kukicha/stdlib/mcp/mcp.kuki:44
func Required(schema any, names []string) any {
//line /var/home/tluker/repos/go/kukicha/stdlib/mcp/mcp.kuki:45
	s, ok := schema.(map[string]any)
//line /var/home/tluker/repos/go/kukicha/stdlib/mcp/mcp.kuki:46
	if !ok {
//line /var/home/tluker/repos/go/kukicha/stdlib/mcp/mcp.kuki:47
		return schema
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/mcp/mcp.kuki:48
	s["required"] = names
//line /var/home/tluker/repos/go/kukicha/stdlib/mcp/mcp.kuki:49
	return s
}

//line /var/home/tluker/repos/go/kukicha/stdlib/mcp/mcp.kuki:52
func TextResult(text string) any {
//line /var/home/tluker/repos/go/kukicha/stdlib/mcp/mcp.kuki:53
	return &mcp.CallToolResult{Content: []mcp.Content{&mcp.TextContent{Text: text}}}
}

//line /var/home/tluker/repos/go/kukicha/stdlib/mcp/mcp.kuki:58
func ErrorResult(msg string) any {
//line /var/home/tluker/repos/go/kukicha/stdlib/mcp/mcp.kuki:59
	return &mcp.CallToolResult{Content: []mcp.Content{&mcp.TextContent{Text: msg}}, IsError: true}
}
