// Generated by Kukicha v0.0.5 (requires Go 1.26+)
//
// Performance: GOEXPERIMENT=jsonv2 enables faster JSON parsing (2-10x improvement)

package mcp

import (
	"context"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

//line /home/user/kukicha/stdlib/mcp/mcp.kuki:9
type ToolHandler func(map[string]any) (any, error)

//line /home/user/kukicha/stdlib/mcp/mcp.kuki:12
type SchemaProperty struct {
	Name        string
	Type        string
	Description string
}

//line /home/user/kukicha/stdlib/mcp/mcp.kuki:18
func New(name string, version string) *mcp.Server {
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:19
	return mcp.NewServer(&mcp.Implementation{Name: name, Version: version}, nil)
}

//line /home/user/kukicha/stdlib/mcp/mcp.kuki:25
func Serve(server *mcp.Server) error {
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:26
	return server.Run(context.Background(), &mcp.StdioTransport{})
}

//line /home/user/kukicha/stdlib/mcp/mcp.kuki:29
func Prop(name string, typ string, description string) SchemaProperty {
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:30
	return SchemaProperty{Name: name, Type: typ, Description: description}
}

//line /home/user/kukicha/stdlib/mcp/mcp.kuki:33
func Schema(props []SchemaProperty) map[string]any {
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:34
	properties := make(map[string]any)
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:35
	for _, prop := range props {
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:39
		properties[prop.Name] = map[string]any{"type": prop.Type, "description": prop.Description}
	}
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:41
	return map[string]any{"type": "object", "properties": properties}
}

//line /home/user/kukicha/stdlib/mcp/mcp.kuki:47
func Required(schema any, names []string) any {
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:48
	switch s := schema.(type) {
	case map[string]any:
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:50
		s["required"] = names
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:51
		return s
	default:
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:53
		return schema
	}
}

//line /home/user/kukicha/stdlib/mcp/mcp.kuki:56
func TextResult(text string) any {
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:57
	return &mcp.CallToolResult{Content: []mcp.Content{&mcp.TextContent{Text: text}}}
}

//line /home/user/kukicha/stdlib/mcp/mcp.kuki:62
func ErrorResult(msg string) any {
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:63
	return &mcp.CallToolResult{Content: []mcp.Content{&mcp.TextContent{Text: msg}}, IsError: true}
}
