// Generated by Kukicha v0.0.5 (requires Go 1.26+)
//
// Performance: GOEXPERIMENT=jsonv2 enables faster JSON parsing (2-10x improvement)

package mcp

import (
	ctxpkg "github.com/duber000/kukicha/stdlib/ctx"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

//line /home/user/kukicha/stdlib/mcp/mcp.kuki:9
type ToolHandler func(map[string]any) (any, error)

//line /home/user/kukicha/stdlib/mcp/mcp.kuki:12
type SchemaProperty struct {
	Name        string
	Type        string
	Description string
}

//line /home/user/kukicha/stdlib/mcp/mcp.kuki:18
func New(name string, version string) *mcp.Server {
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:19
	return mcp.NewServer(&mcp.Implementation{Name: name, Version: version}, nil)
}

//line /home/user/kukicha/stdlib/mcp/mcp.kuki:25
func Serve(server *mcp.Server) error {
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:26
	bg := ctxpkg.Background()
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:27
	return server.Run(ctxpkg.Value(bg), &mcp.StdioTransport{})
}

//line /home/user/kukicha/stdlib/mcp/mcp.kuki:30
func Prop(name string, typ string, description string) SchemaProperty {
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:31
	return SchemaProperty{Name: name, Type: typ, Description: description}
}

//line /home/user/kukicha/stdlib/mcp/mcp.kuki:34
func Schema(props []SchemaProperty) map[string]any {
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:35
	properties := make(map[string]any)
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:36
	for _, prop := range props {
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:40
		properties[prop.Name] = map[string]any{"type": prop.Type, "description": prop.Description}
	}
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:42
	return map[string]any{"type": "object", "properties": properties}
}

//line /home/user/kukicha/stdlib/mcp/mcp.kuki:48
func Required(schema any, names []string) any {
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:49
	switch s := schema.(type) {
	case map[string]any:
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:51
		s["required"] = names
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:52
		return s
	default:
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:54
		return schema
	}
}

//line /home/user/kukicha/stdlib/mcp/mcp.kuki:57
func TextResult(text string) any {
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:58
	return &mcp.CallToolResult{Content: []mcp.Content{&mcp.TextContent{Text: text}}}
}

//line /home/user/kukicha/stdlib/mcp/mcp.kuki:63
func ErrorResult(msg string) any {
//line /home/user/kukicha/stdlib/mcp/mcp.kuki:64
	return &mcp.CallToolResult{Content: []mcp.Content{&mcp.TextContent{Text: msg}}, IsError: true}
}
