// Generated by Kukicha v0.0.4 (requires Go 1.26+)
//
// Performance: GOEXPERIMENT=jsonv2 enables faster JSON parsing (2-10x improvement)

package fetch

import (
	"bytes"
	"encoding/base64"
	"errors"
	"fmt"
	"github.com/duber000/kukicha/stdlib/json"
	"github.com/duber000/kukicha/stdlib/sandbox"
	"io"
	"net/http"
	"net/http/cookiejar"
	"net/url"
	"strings"
	"time"
)

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:29
type Request struct {
	url       string
	headers   map[string]string
	timeoutNs int64
	method    string
	body      any
	transport *http.Transport
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:40
func New(url string) Request {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:41
	req := Request{}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:42
	req.url = url
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:43
	req.headers = make(map[string]string)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:44
	req.timeoutNs = 30000000000
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:45
	req.method = "GET"
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:46
	req.body = nil
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:47
	return req
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:51
func Header(req Request, name string, value string) Request {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:52
	req.headers[name] = value
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:53
	return req
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:58
func Timeout(req Request, durationNs int64) Request {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:59
	req.timeoutNs = durationNs
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:60
	return req
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:64
func Method(req Request, method string) Request {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:65
	req.method = method
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:66
	return req
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:71
func Body(req Request, data any) Request {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:72
	req.body = data
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:73
	return req
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:78
func Transport(req Request, t *http.Transport) Request {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:79
	req.transport = t
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:80
	return req
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:85
func Do(req Request) (*http.Response, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:86
	client := http.Client{}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:87
	if req.transport != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:88
		client.Transport = req.transport
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:89
	client.Timeout = time.Duration(req.timeoutNs)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:93
	var bodyData interface{}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:94
	if req.body != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:96
		switch bodyStr := req.body.(type) {
		case string:
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:98
			bodyData = []byte(bodyStr)
		default:
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:101
			jsonBytes, marshalErr := json.Marshal(req.body)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:102
			if marshalErr != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:103
				return nil, marshalErr
			}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:104
			bodyData = jsonBytes
		}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:106
	httpReq, reqErr := createHTTPRequest(req.method, req.url, bodyData)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:107
	if reqErr != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:108
		return nil, reqErr
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:111
	for name, value := range req.headers {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:112
		httpReq.Header.Set(name, value)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:115
	if req.body != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:116
		contentType := httpReq.Header.Get("Content-Type")
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:117
		if contentType == "" {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:118
			httpReq.Header.Set("Content-Type", "application/json")
		}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:120
	resp, doErr := client.Do(httpReq)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:121
	return resp, doErr
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:124
func createHTTPRequest(method string, url string, bodyData any) (*http.Request, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:125
	if bodyData != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:126
		bodyBytes := bodyData.([]byte)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:127
		req, err := http.NewRequest(method, url, bytes.NewReader(bodyBytes))
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:128
		return req, err
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:129
	req, err := http.NewRequest(method, url, nil)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:130
	return req, err
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:135
func Get(url string) (*http.Response, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:136
	req := New(url)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:137
	resp, err := Do(req)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:138
	return resp, err
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:144
func Post(data any, url string) (*http.Response, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:145
	req := New(url)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:146
	req = Method(req, "POST")
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:147
	req.body = data
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:148
	resp, err := Do(req)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:149
	return resp, err
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:154
func CheckStatus(resp *http.Response) (*http.Response, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:155
	if resp.StatusCode >= 400 {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:156
		return nil, errors.New(fmt.Sprintf("request failed: %v", resp.Status))
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:157
	return resp, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:161
func Text(resp *http.Response) (string, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:162
	defer resp.Body.Close()
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:163
	bodyBytes, err := io.ReadAll(resp.Body)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:164
	if err != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:165
		return "", err
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:167
	text := string(bodyBytes)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:168
	return text, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:173
func Bytes(resp *http.Response) ([]byte, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:174
	defer resp.Body.Close()
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:175
	bodyBytes, err := io.ReadAll(resp.Body)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:176
	if err != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:177
		return nil, err
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:178
	return bodyBytes, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:183
func Json[T any](resp *http.Response, sample T) (T, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:184
	defer resp.Body.Close()
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:185
	data := sample
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:186
	if err_1 := json.UnmarshalRead(resp.Body, &data); err_1 != nil {
		err_1 = fmt.Errorf("failed to decode response json: %w", err_1)
		return *new(T), err_1
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:187
	return data, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:194
func Decode(resp *http.Response, target any) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:195
	defer resp.Body.Close()
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:196
	return json.UnmarshalRead(resp.Body, target)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:200
func PathEscape(value string) string {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:201
	return url.PathEscape(value)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:205
func QueryEscape(value string) string {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:206
	return url.QueryEscape(value)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:212
func URLTemplate(tmpl string, params map[string]string) (string, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:213
	result := tmpl
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:214
	for key, value := range params {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:215
		placeholder := fmt.Sprintf("%c%s%c", 123, key, 125)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:216
		result = strings.ReplaceAll(result, placeholder, url.PathEscape(value))
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:218
	if strings.Contains(result, "{") || strings.Contains(result, "}") {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:219
		return "", errors.New(fmt.Sprintf("unresolved URL template placeholders: %v", result))
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:220
	return result, nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:225
func URLWithQuery(baseURL string, params map[string]string) (string, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:226
	parsed, err := url.Parse(baseURL)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:227
	if err != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:228
		return "", err
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:229
	query := parsed.Query()
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:230
	for key, value := range params {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:231
		query.Set(key, value)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:232
	parsed.RawQuery = query.Encode()
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:233
	return parsed.String(), nil
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:241
func BearerAuth(req Request, token string) Request {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:242
	return Header(req, "Authorization", fmt.Sprintf("Bearer %v", token))
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:246
func BasicAuth(req Request, username string, password string) Request {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:247
	credentials := fmt.Sprintf("%v:%v", username, password)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:248
	encoded := base64.StdEncoding.EncodeToString([]byte(credentials))
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:249
	return Header(req, "Authorization", fmt.Sprintf("Basic %v", encoded))
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:258
func FormData(req Request, data map[string]string) Request {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:259
	values := url.Values{}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:260
	for key, value := range data {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:261
		values.Set(key, value)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:262
	req.body = values.Encode()
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:263
	req = Header(req, "Content-Type", "application/x-www-form-urlencoded")
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:264
	return req
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:271
type Session struct {
	client    http.Client
	headers   map[string]string
	timeoutNs int64
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:278
func NewSession() Session {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:279
	jar, _ := cookiejar.New(nil)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:280
	client := http.Client{Jar: jar}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:281
	s := Session{}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:282
	s.client = client
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:283
	s.headers = make(map[string]string)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:284
	s.timeoutNs = 30000000000
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:285
	return s
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:289
func SessionHeader(s Session, name string, value string) Session {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:290
	s.headers[name] = value
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:291
	return s
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:295
func SessionTimeout(s Session, durationNs int64) Session {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:296
	s.timeoutNs = durationNs
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:297
	return s
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:302
func SessionDo(s Session, req Request) (*http.Response, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:304
	for name, value := range s.headers {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:305
		_, exists := req.headers[name]
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:306
		if !exists {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:307
			req.headers[name] = value
		}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:310
	if req.timeoutNs == 30000000000 {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:311
		req.timeoutNs = s.timeoutNs
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:314
	s.client.Timeout = time.Duration(req.timeoutNs)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:317
	var bodyData interface{}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:318
	if req.body != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:320
		switch bodyStr := req.body.(type) {
		case string:
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:322
			bodyData = []byte(bodyStr)
		default:
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:324
			jsonBytes, marshalErr := json.Marshal(req.body)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:325
			if marshalErr != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:326
				return nil, marshalErr
			}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:327
			bodyData = jsonBytes
		}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:329
	httpReq, reqErr := createHTTPRequest(req.method, req.url, bodyData)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:330
	if reqErr != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:331
		return nil, reqErr
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:333
	for name, value := range req.headers {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:334
		httpReq.Header.Set(name, value)
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:337
	if req.body != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:338
		contentType := httpReq.Header.Get("Content-Type")
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:339
		if contentType == "" {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:340
			httpReq.Header.Set("Content-Type", "application/json")
		}
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:342
	resp, doErr := s.client.Do(httpReq)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:343
	return resp, doErr
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:347
func SessionGet(s Session, url string) (*http.Response, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:348
	req := New(url)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:349
	return SessionDo(s, req)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:353
func SessionPost(s Session, data any, url string) (*http.Response, error) {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:354
	req := New(url)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:355
	req = Method(req, "POST")
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:356
	req.body = data
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:357
	return SessionDo(s, req)
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:362
func SessionTransport(s Session, t *http.Transport) Session {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:363
	s.client.Transport = t
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:364
	return s
}

//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:372
func DownloadTo(resp *http.Response, box sandbox.Root, path string) error {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:373
	defer resp.Body.Close()
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:374
	bodyBytes, err := io.ReadAll(resp.Body)
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:375
	if err != nil {
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:376
		return err
	}
//line /var/home/tluker/repos/go/kukicha/stdlib/fetch/fetch.kuki:377
	return sandbox.WriteString(box, string(bodyBytes), path)
}
